// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFRq1uolD8GQRgGd8sI6pan8LzvvS1Mxk',
    appId: '1:389872967993:web:fe880ec2dbe1ef1a04c8e8',
    messagingSenderId: '389872967993',
    projectId: 'talkboard-b93dd',
    authDomain: 'talkboard-b93dd.firebaseapp.com',
    storageBucket: 'talkboard-b93dd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEjewknPeEhdICNnFrIlFdaA_ASlgjHAw',
    appId: '1:389872967993:android:96ccc791723034c504c8e8',
    messagingSenderId: '389872967993',
    projectId: 'talkboard-b93dd',
    storageBucket: 'talkboard-b93dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiBrZA02XUWXIWjyOO-W5qeNlDih8fH7U',
    appId: '1:389872967993:ios:a7d3ebec1b51435004c8e8',
    messagingSenderId: '389872967993',
    projectId: 'talkboard-b93dd',
    storageBucket: 'talkboard-b93dd.firebasestorage.app',
    iosBundleId: 'com.talkboard.app',
  );

}