// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP8GwSu7uXIbzXV-fFpmcGTs1B3SvufmQ',
    appId: '1:13173094667:android:e3fbfd3b91bc12b2594a0e',
    messagingSenderId: '13173094667',
    projectId: 'freeboard-501e6',
    storageBucket: 'freeboard-501e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC425us_hSmuoKzsRtrlNuGGAe1jrRXaaI',
    appId: '1:13173094667:ios:a84ccf85d2350649594a0e',
    messagingSenderId: '13173094667',
    projectId: 'freeboard-501e6',
    storageBucket: 'freeboard-501e6.firebasestorage.app',
    iosBundleId: 'com.freeboard.freeBoard',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTMSu2aBrPzt8f459gfVfGylxttoLo894',
    appId: '1:13173094667:web:f616ec59ad23d389594a0e',
    messagingSenderId: '13173094667',
    projectId: 'freeboard-501e6',
    authDomain: 'freeboard-501e6.firebaseapp.com',
    storageBucket: 'freeboard-501e6.firebasestorage.app',
  );

}