include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/screens/preview_screens/**
    - lib/screens/components_guide_screen.dart
    - lib/screens/database_diagram_screen.dart
    - lib/utils/sample_data_generator.dart
    - lib/utils/migrate_data.dart
  errors:
    avoid_print: warning

linter:
  rules:
    # Naming consistency
    file_names: true
    library_names: true
    constant_identifier_names: true

    # Style & safety
    always_use_package_imports: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    use_build_context_synchronously: true
